### PR TITLE
Secure default file.dir

### PR DESCRIPTION
**Pull request by immetoo**
Just wanted to change /tmp to better default like '.'
So added some tests and missing config wiring.
But could not get the Undertow working it correctly, have it now working but not nice.
Could you have a look or hint how that should work ?

Maybe other solution is to leave out container based file hosting and providing own file servlet ?
(also makes config and behaviour consistent over all containers)

### CODE REVIEW

**Comment by johnament** [comment]
Can you rebase from master? It's hard to tell what's supposed to be in this PR.

**Comment by johnament** [comment]
Also, can you create an issue indicating you're changing the default dir from `/tmp` to `.`

**Comment by immetoo** [comment]
Have merged master in.
As that Undertow fix should not be merged in current state, im doing something wrong but can figure how it should done, so maybe you have some advice ?

But while thinking over it my preference would to go with an container independent servlet solution for consistency.

**Comment by johnament** [comment]
Yeah, basically this changes quite a bit.  I'd recommend starting over.

So right now, `file.dir` is only used for Jetty, and its used as the context root path.  You are correct, jetty and tomcat are inconsistent in this fashion.  However, I'm not sure what you're aiming to do with this change.  The use within Jetty is if you have custom Jetty config files they can be hosted in this path.  Tomcat does the equivalent, but using the hard coded path of `.` (so you're correct to remove that).  I'm not actually sure that Undertow has the same feature, I think what you're doing is trying to serve static assets.  It's purposely `/tmp` which is not really going to be useful to avoid possible bad contents.

Static asset serving is done via [ResourceManager](https://github.com/hammock-project/hammock/blob/master/web-spi/src/main/java/ws/ament/hammock/web/resource/ResourceManager.java) which purposely only handling classpath resources, the default config looking at `META-INF/resources/`.  I will not merge in a PR that is designed to host static files from the file system due to the inherent security issues.  If you're looking to do something via a dev mode, I'd recommend tools like webpack or grunt to host your frontend on top of the backend, otherwise you can use Hammock to load from the classpath (though do take caution to not move this outside of `/META-INF` or else your underlying class files will be at risk.

So what are you aiming to get out of this?

**Comment by immetoo** [comment]
Your right, lets close this and try again from issue.
I was only trying to add an simple unit test of that config property :)

**Pull request closed without merging**
