### PR TITLE
upgrade to Swagger 2.0.0-rc4

### PR DESCRIPTION
**Pull request by derekm**
Signed-off-by: Derek P. Moore <dpmoore@acm.org>

### CODE REVIEW

**Comment by derekm** [comment]
Oops, nevermind! Swagger 2.0.0-rc4 isn't CDI-enabled! My commits are merged immediately after rc4 was cut... My commits need to survive feedback from integrators in SNAPSHOT to make it into rc5, apparently.

**Comment by johnament** [comment]
So hold on this, right?

**Comment by derekm** [comment]
I could change this PR to an rc4 upgrade only. I was wrong about the CDI-ification being included yet. I have outstanding commits that change to a SNAPSHOT version where we do have CDI-ification, but then it is down some kind of Arquillian rabbit hole to get the swagger dependency loaded via the pom definition as would happen at runtime with bean discovery instead of being explicitly added to a JavaArchive, which skips testing the dependency's beans.xml.

A more traditional JUnit test that does a manual SeContainer might be a better way of testing the CDI-ification of the Swagger dependency. ... But that PR can come later, and this PR can be an upgrade to rc4 w/o deleting the wrapper objects.

I do need to keep a good example of the SNAPSHOT upgrade with deleted wrapper objects around for the issues in: https://github.com/swagger-api/swagger-core/pull/2627

**Comment by derekm** [comment]
Actually, I think this rc4 upgrade allows us to remove the Guava dependency now...

**Comment by derekm** [comment]
Hmm... Looks like you didn't need to declare the Guava and Jackson dependencies. They must already be loaded? https://github.com/hammock-project/hammock/blob/master/swagger/pom.xml

**Comment by johnament** [comment]
Guava and Jackson should come in as transitive dependencies.

**Pull request merged**
