### PR TITLE
#34 Jersey integration

### PR DESCRIPTION
**Pull request by shamoh**
This is my initial Jersey integration.

### CODE REVIEW

**Comment by shamoh** [comment]
This implements issue #34.

**Comment by johnament** [comment]
Did you want to direct this to master or the separate branch? I'd prefer master.  That branch was just because you asked ;-)

Thanks for the contrib!

**Comment by johnament** [comment]
LGTM

**Comment by shamoh** [comment]
Master for sure.

**Comment by johnament** [comment]
Can you change your commit messages to include the ticket #?

**Comment by shamoh** [comment]
Is it ok now?

**Comment by shamoh** [comment]
@johnament, please, do not accept it yet. ;)
I will add ApplicationPath.value support.

**Comment by johnament** [comment]
@shamoh sure take your time.  Looks good.

**Comment by johnament** [comment]
Oh wait, the commit messages don't have it.  Can you rebase your commits and edit your commit message?

**Comment by shamoh** [comment]
I'm going to prepare another PR.

**Comment by shamoh** [comment]
@johnament See my new PR #37.

**Pull request closed without merging**
