### PR TITLE
Sslsupport

### PR DESCRIPTION
**Pull request by irimia-dragos**

### CODE REVIEW

**Comment by irimia-dragos** [comment]
Sorry, I'm still new to git (I've only used subversion so far) and I'm stilll learning.
It's OK to have both commits in 2 different PR's ?

**Comment by johnament** [comment]
Hi @irimia-dragos the second PR isn't required.  Up to you which you want to keep around.  The code changes look good.  However, there's no tests.  Would you mind adding SSL based tests?

If you're looking for resources on git you may want to use https://help.github.com/articles/good-resources-for-learning-git-and-github/ as a base of operations.  I would probably squash these commits, but at a bare minimum include the ticket # in the commit.

**Comment by irimia-dragos** [comment]
I've added a test on the UndertowBootTest.
In this test I've only tested for open port.
There is no ssl trafic, because I should have added the certificate in trusted certs before open the ssl connection.
There is a problem configuring deltaspike for different tests. I've added a HammockTestPropertyFileConfig class in order to set a custom property file.

I think that the best approach would be to have a single test, and run it against web-tomcat, web-jetty, and web-undertow. Maybe we could have different profiles, as in the rest modules.

**Comment by johnament** [comment]
I wouldn't try to lump this into the existing undertow boot test, but instead create a new one.  Since DeltaSpike provides an SPI for registering PropertySourceProviders, may be use that to register the custom property source? Otherwise static methods?

We should check that you're able to make the request.  Even if its using a self signed cert.

**Comment by irimia-dragos** [comment]
Right, but this test should still be in the web-undertow project?
For PropertySourceProviders do you have any tips? Right now it's using a static field to add a test hammoc-test.properties.  You mean use a static setter for this field?

For testing, I think it means we're adding a custom TrustManager, like this http://stackoverflow.com/a/6755459  Are you OK with that?

**Comment by johnament** [comment]
Yep, i'm fine with it.  And test location is correct - we just need to make sure equivalent tests are available for Jetty and Tomcat.

**Comment by johnament** [comment]
I merged via a squash, there were many commits in here.  You'll need to pull and `git push -f`.  You're awesome!

**Pull request merged**
